USE [SA45TEAM04_BOOKSTORE]
GO

/****** Object:  Index [PK_Book]    Script Date: 20/11/2017 4:21:21 PM ******/
ALTER TABLE [dbo].[Book] ADD  CONSTRAINT [PK_Book] PRIMARY KEY CLUSTERED 
(
	[BookID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


USE [SA45TEAM04_BOOKSTORE]
GO

ALTER TABLE [dbo].[Book]  WITH CHECK ADD  CONSTRAINT [FK_Book_Category] FOREIGN KEY([CategoryID])
REFERENCES [dbo].[Category] ([CategoryID])
GO

ALTER TABLE [dbo].[Book] CHECK CONSTRAINT [FK_Book_Category]
GO


USE [SA45TEAM04_BOOKSTORE]
GO

/****** Object:  Index [PK_Category]    Script Date: 20/11/2017 4:21:54 PM ******/
ALTER TABLE [dbo].[Category] ADD  CONSTRAINT [PK_Category] PRIMARY KEY CLUSTERED 
(
	[CategoryID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


